### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by rickardp** [ricott/homey-no.easee#18] opened 2022-02-13 21:08 UTC
My Easee units stopped reporting on Feb 1. I tried removing and re-adding. I got past the login screen and the devices were detected (charger and equalizer), but none of them report any data anymore. The devices work as expected from the Easee app.

Could it be an API change or firmware update? Any other reports of this?

The charger is firmware v294 (do not remember if it was the same or different before unfortunately). Equalizer is v102.

**Comment by ricott** [comment] 2022-02-13 21:25
In the last couple of versions, I have been doing multiple changes related to IT grid mapping. Could it be that you have an IT grid?

If that is the case, can you share what you find in the advanced settings on the devices under "Last stream messages".
Interested in this for both charger and equalizer.

**Comment by rickardp** [comment] 2022-02-14 09:05
Those fields were empty. I will install the app from Github to see what the log says.

Pardon my ignorance, what is an “IT grid”?

**Comment by rickardp** [comment] 2022-02-16 22:52
Ah I thought that term was related to how the devices communicated. After some read up, I'm happy to have a good old Swedish three phase connection with a proper neutral :)

As for running it locally, I failed (see stacktrace below). Do you have the steps needed to build and run locally?

```
Warning: Trying to access `Homey.env.ENCRYPTION_KEY` but the environment variable has not been set!
Device.onInit Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:313:9)
    at ChargerDevice.decryptText (/drivers/charger/device.js:434:66)
    at ChargerDevice.getUsername (/drivers/charger/device.js:416:21)
    at ChargerDevice.onInit (/drivers/charger/device.js:94:42)
    at ChargerDevice._onInit (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js:134:18)
    at /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Driver.js:182:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by rickardp** [comment] 2022-02-16 23:08
Ah I see now what you do. I wasn't able to get the password encryption to work so I deleted it and I'll try again.
(On a separate note I don't think doing this adds security as the .env file seems to be stored in plaintext on the device, but I'm not sure what the intent is).

**Comment by rickardp** [comment] 2022-02-16 23:44
Update: when installing locally it works, when installing from the store I don't get updates. Are there unreleased changes?

**Comment by ricott** [comment] 2022-02-17 08:13
>Homey.env.ENCRYPTION_KEY

Right, this was added such a long time ago I forgot about it. 
https://apps.developer.homey.app/the-basics/app#environment

in the root folder, you need a file named `env.json` with the following content.
```
{
    "ENCRYPTION_KEY": "<32 character long key>"
}
```

**Comment by rickardp** [comment] 2022-02-19 17:38
I tried that earlier but I got an error from the encryption library.  Probably it expects some format?
Anyway I commented out all the encryption code and got it to run, and the local build works for me but when I use the one from the store I don't see any values, although I can add the devices just fine. (The encryption forces me to delete all devices and re-add them every time, so I know both started off from a clean state)

**Comment by ricott** [comment] 2022-03-02 08:25
For that, I must say I'm clueless about how you can see values when deployed via CLI and otherwise not. There are 2000+ installs of the app and this I have never heard of.

About encryption, I can't give you the key I'm using. So you would need to remove the devices and enter a 32 char key as per above and then it should work fine. The key you create must be exactly 32 chars long.

**Comment by ricott** [comment] 2022-07-29 08:49
Lots of changes since this ticket was created, closing. 
Open a new ticket when using the latest app version, if the problem is still there.

**Closed by ricott** 2022-07-29 08:49 UTC
