### ISSUE TITLE
Doesn't update value

### ISSUE THREAD

**Issue by mzaar86** [ricott/homey-no.easee#25] opened 2022-06-18 07:44 UTC
Hi. Im not geting any new values in to my Homey Pro. The Equalizer works fine and I get all the correct usage in the easee app.

**Comment by ricott** [comment] 2022-07-05 19:33
Hi!
It is extremely hard to diagnose anything based on this description. I have however a new rewrite of the app running locally removing the SignalR API and using the plain REST API. Will not push it before I go on vacation though, so expect it towards the end of July. There are however close to 3000 installs of the app, and if the Charger device wouldn't work on any of them I'm pretty sure there would be lots of issues reported here.

**Comment by ricott** [comment] 2022-07-06 16:13
I got access to an equalizer from Easee and decided to release the test version 1.4.0 - please give it a go.

**Comment by ricott** [comment] 2022-07-29 08:49
Lots of changes since this ticket was created, closing. 
Open a new ticket when using the latest app version, if the problem is still there.

**Closed by ricott** 2022-07-29 08:49 UTC
